paragaps_noun_map = {'accounts': 'account',
           'applications': 'application',
           'nails': 'nail',
           'teeth': 'tooth',
           'fingers': 'finger',
           'phones': 'phone',
           'resources': 'resource',
           'prices': 'price',
           'defendants': 'defendant',
           'balls': 'ball',
           'englishman': 'man'}

paragaps_verb_map = {'possessing': 'possess', 'accused': 'accuse',
                     'scoring': 'score', 'convicting': 'convict',
                     'arresting': 'arrest', 'swallowing': 'swallow',
                     'inspecting': 'inspect', 'discovering': 'discover',
                     'increasing': 'increase', 'tapped': 'tap', 'smoothed': 'smooth',
                     'calculating': 'calculate', 'registered': 'register',
                     'noticing': 'notice', 'sipping': 'sip', 'touching': 'touch',
           'filed': 'file',
           'billed': 'bill',
           'dribbled': 'dribble',
           'reading': 'read',
           'carried': 'carry',
           'intercepted': 'intercept',
           'dripped': 'drip',
           'filling': 'fill',
           'cutting': 'cut',
           'knocked': 'knock',
           'charged': 'charge',
           'diverting': 'divert',
           'softening': 'soften',
           'spitting': 'spit',
           'braiding': 'braid',
           'seizing': 'seize',
           'modifying': 'modify',
           'pulling': 'pull',
           'reviewing': 'review',
           'displaying': 'display',
           'wooing': 'woo',
        'burning': 'burn',
        'registering': 'register',
        'tasting': 'taste',
        'destroying': 'destroy',
        'abstaining': 'abstain',
        'decoding': 'decode',
        'hitting': 'hit',
        'democratising': 'democratise',
        'receiving': 'receive',
        'generating': 'generate',
        'eating': 'eat',
        'buckling': 'buckle',
        'initiated': 'initiate',
        'condemning': 'condemn',
        'leaking': 'leak',
        'approving': 'approve',
        'kicking': 'kick',
        'embroidering': 'embroider',
        'tying': 'tie',
        'redirecting': 'redirect',
        'decentralising': 'decentralise',
        'radiating': 'radiate',
        'shaking': 'shake',
        'banging': 'bang',
        'fighting': 'fight',
        'apologising': 'apologise',
        'supervised': 'supervise',
        'submitting': 'submit',
        'polishing': 'polish',
        'tightening': 'tighten',
        'strapping': 'strap',
        'flooding': 'flood',
        'playing': 'play',
        'juggling': 'juggle'}
